-- Create a table for public messages
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID NOT NULL REFERENCES auth.users(id),
  receiver_id UUID NOT NULL REFERENCES auth.users(id),
  content TEXT,
  file_url TEXT,
  file_type TEXT, -- e.g., 'image', 'video'
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  read_at TIMESTAMPTZ
);

-- Add indexes for performance
CREATE INDEX messages_sender_id_idx ON messages(sender_id);
CREATE INDEX messages_receiver_id_idx ON messages(receiver_id);
CREATE INDEX messages_created_at_idx ON messages(created_at);

-- Create a storage bucket for message attachments
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('message_attachments', 'message_attachments', TRUE, 52428800, ARRAY['image/jpeg', 'image/png', 'video/mp4', 'image/gif']); -- 50MB limit

-- Set up RLS policies
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to see their own messages"
ON messages
FOR SELECT
USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Allow users to send messages"
ON messages
FOR INSERT
WITH CHECK (auth.uid() = sender_id);

-- Enable real-time on the messages table
ALTER PUBLICATION supabase_realtime ADD TABLE messages; 