// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elacivprlvyceqbwmylh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsYWNpdnBybHZ5Y2VxYndteWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjM3MzYsImV4cCI6MjA1OTA5OTczNn0.gCGjrMJcvvzqx7EeN6UUX6dQyi3Mx5s0GCME5OjlkVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);